# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

any_parallels__ <- function(start, end) {
    .Call(`_voicer_any_parallels__`, start, end)
}

any_parallels_ <- function(context, continuation) {
    .Call(`_voicer_any_parallels_`, context, continuation)
}

